defaults:
  - misc_train
  - dataset: cifar10
  - optimizer: sgd
  - scheduler: multisteplr

hydra:
  run:
    dir: ../logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}