defaults:
  - misc/misc_shared
  - misc/misc_train
  - online_logger: comet
  - dataset: cifar10
  - optimizer: sgd
  - scheduler: multisteplr
  - augmentation: standard

hydra:
  job:
    config:
      override_dirname:
        exclude_keys: ['resume_ckpt_path']
  run:
    dir: ../logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ../logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}